title: Kushal Mohnot # your name (or website title) here
logo: "/images/IMG_2746.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Looking for full time positions in Data Analysis/Statistics. Proficient in Python and R with a strong theoretical background in Math/Statistics and Biology. 
  <br><br>
  CSULB MS in Applied Statistics - 2021
  UCLA BS in Computational and Systems Biology, minor in Mathematics - 2019
  Top 95 percentile of Python programmers on DataCamp
  <br><br>
  <a href="https://www.linkedin.com/in/kushal-mohnot-41b64a12a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
